server:
  port: 9092
spring:
  cloud:
    discovery:
      client:
        simple:
          instances:
            test:
              - uri: http://192.168.11.141:8080
                metadata:
                  management.context-path: /